### ISSUE TITLE
Timer trigger crashes if you do not set startDate, hours, minutes or seconds

### ISSUE THREAD

**Issue by ecarlier-tibco** [TIBCOSoftware/flogo-contrib#117]
It works fine when running it from flogo-web, but it crashes with a panic when you run it from a generated binary.

Here is what you get if you do not set startDate:
```
panic: interface conversion: interface is nil, not string

goroutine 1 [running]:
panic(0x394820, 0x108e2180)
	/usr/local/go/src/runtime/panic.go:500 +0x33c
github.com/TIBCOSoftware/flogo-contrib/trigger/timer.getInitialStartInSeconds(0x108b59c0, 0x1080aaf0)
	/tmp/flogo-web/build/server/local/engines/app-build/vendor/src/github.com/TIBCOSoftware/flogo-contrib/trigger/timer/timer.go:177 +0x100
github.com/TIBCOSoftware/flogo-contrib/trigger/timer.(*TimerTrigger).scheduleRepeating(0x108b5ce0, 0x108b59c0)
	/tmp/flogo-web/build/server/local/engines/app-build/vendor/src/github.com/TIBCOSoftware/flogo-contrib/trigger/timer/timer.go:131 +0xd8
github.com/TIBCOSoftware/flogo-contrib/trigger/timer.(*TimerTrigger).Start(0x108b5ce0, 0x0, 0x0)
	/tmp/flogo-web/build/server/local/engines/app-build/vendor/src/github.com/TIBCOSoftware/flogo-contrib/trigger/timer/timer.go:68 +0x6dc
github.com/TIBCOSoftware/flogo-lib/util.StartManaged(0x108e20c0, 0x13, 0x76e853a8, 0x108b5ce0, 0x0, 0x0)
	/tmp/flogo-web/build/server/local/engines/app-build/vendor/src/github.com/TIBCOSoftware/flogo-lib/util/managed.go:62 +0xe8
github.com/TIBCOSoftware/flogo-lib/engine.(*EngineConfig).Start(0x108b5c00)
	/tmp/flogo-web/build/server/local/engines/app-build/vendor/src/github.com/TIBCOSoftware/flogo-lib/engine/engine.go:138 +0xac0
main.main()
	/tmp/flogo-web/build/server/local/engines/app-build/src/app-build/main.go:37 +0x234
```
Here is what you get if you do not set hours or minutes:

```
panic: interface conversion: interface is nil, not string

goroutine 1 [running]:
panic(0x3868a0, 0xc420091280)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/TIBCOSoftware/flogo-contrib/trigger/timer.(*TimerTrigger).scheduleJobEverySecond(0xc4200ebdd0, 0xc4200eba40, 0xc42011d2e0)
	/tmp/flogo-web/build/server/local/engines/app-build/vendor/src/github.com/TIBCOSoftware/flogo-contrib/trigger/timer/timer.go:246 +0x154
github.com/TIBCOSoftware/flogo-contrib/trigger/timer.(*TimerTrigger).scheduleRepeating(0xc4200ebdd0, 0xc4200eba40)
	/tmp/flogo-web/build/server/local/engines/app-build/vendor/src/github.com/TIBCOSoftware/flogo-contrib/trigger/timer/timer.go:147 +0x227
github.com/TIBCOSoftware/flogo-contrib/trigger/timer.(*TimerTrigger).Start(0xc4200ebdd0, 0xf, 0xc4200fbd00)
	/tmp/flogo-web/build/server/local/engines/app-build/vendor/src/github.com/TIBCOSoftware/flogo-contrib/trigger/timer/timer.go:68 +0x688
github.com/TIBCOSoftware/flogo-lib/util.StartManaged(0xc42011cf20, 0x13, 0x6c5610, 0xc4200ebdd0, 0xc4200ebdd0, 0xc42011cf20)
	/tmp/flogo-web/build/server/local/engines/app-build/vendor/src/github.com/TIBCOSoftware/flogo-lib/util/managed.go:62 +0xf4
github.com/TIBCOSoftware/flogo-lib/engine.(*EngineConfig).Start(0xc4200ebce0)
	/tmp/flogo-web/build/server/local/engines/app-build/vendor/src/github.com/TIBCOSoftware/flogo-lib/engine/engine.go:138 +0x7a1
main.main()
	/tmp/flogo-web/build/server/local/engines/app-build/src/app-build/main.go:37 +0xb7

```
Cheers
Eric

**Comment by retgits** [comment]
Hi Eric,

With the current version of flogo-contrib (0.5.4) this issue should be fixed. Would you be able to confirm?

**Comment by ecarlier-tibco** [comment]
Hi Leon,

Yes indeed. I used it last time and it was working as expected.

Thanks!
