### ISSUE TITLE
Return activity fails with new mapping type labels

### ISSUE THREAD

**Issue by fcastill** [TIBCOSoftware/flogo-contrib#217]
I tried creating an simple flow that just echoes a path parameter. If I use the new mapping labels for the return mappings I get an error `interface conversion: interface {} is string, not float64`/

With this configuration fails:
```
{
   "id":"actreturn_3",
   "activity":{
      "ref":"github.com/TIBCOSoftware/flogo-contrib/activity/actreturn",
      "input":{
         "mappings":[
            {
               "mapTo":"output",
               "type": "assign",
               "value":"$flow.input"
            }
         ]
      }
   }
}
```

But this one works:
```
{
   "id":"actreturn_3",
   "activity":{
      "ref":"github.com/TIBCOSoftware/flogo-contrib/activity/actreturn",
      "input":{
         "mappings":[
            {
               "mapTo":"output",
               "type": 1,
               "value":"$flow.input"
            }
         ]
      }
   }
}
```

## App I'm using to test:
```
{
  "name": "return-6",
  "type": "flogo:app",
  "version": "0.0.1",
  "appModel": "1.0.0",
  "triggers": [
    {
      "id": "receive_http_message",
      "ref": "github.com/TIBCOSoftware/flogo-contrib/trigger/rest",
      "name": "Receive HTTP Message",
      "description": "Simple REST Trigger",
      "settings": {
        "port": "8888"
      },
      "handlers": [
        {
          "action": {
            "ref": "github.com/TIBCOSoftware/flogo-contrib/action/flow",
            "data": {
              "flowURI": "res://flow:returnflow"
            },
            "mappings": {
              "input": [
                {
                  "mapTo": "input",
                  "type": "assign",
                  "value": "params.message"
                }
              ],
              "output": [
                {
                  "mapTo": "code",
                  "type": "literal",
                  "value": 200
                },
                {
                  "mapTo": "data",
                  "type": "object",
                  "value": {
                    "message": "{{ output }}"
                  }
                }
              ]
            }
          },
          "settings": {
            "method": "GET",
            "path": "/echo/:message"
          }
        }
      ]
    }
  ],
  "resources": [
    {
      "id": "flow:returnflow",
      "data": {
        "name": "returnflow",
        "metadata": {
          "input": [
            {
              "name": "input",
              "type": "string"
            }
          ],
          "output": [
            {
              "name": "output",
              "type": "string"
            }
          ]
        },
        "tasks": [
          {
            "id": "log_2",
            "activity": {
              "ref": "github.com/TIBCOSoftware/flogo-contrib/activity/log",
              "input": {
                "message": "log ",
                "flowInfo": "true",
                "addToFlow": "true"
              }
            }
          },
          {
            "id": "actreturn_3",
            "activity": {
              "ref": "github.com/TIBCOSoftware/flogo-contrib/activity/actreturn",
              "input": {
                "mappings": [
                  {
                    "mapTo": "output",
                    "type": "assign",
                    "value": "$flow.input"
                  }
                ]
              }
            }
          }
        ],
        "links": [
          {
            "from": "log_2",
            "to": "actreturn_3"
          }
        ]
      }
    }
  ]
}
```

## Logs for the error:

```
2018-03-05 19:28:38.869 DEBUG  [engine] - Registering activity: 'github.com/TIBCOSoftware/flogo-contrib/activity/log'
2018-03-05 19:28:38.869 DEBUG  [engine] - Registering activity: 'github.com/TIBCOSoftware/flogo-contrib/activity/actreturn'
2018-03-05 19:28:38.869 INFO   [engine] - Engine: Starting...
2018-03-05 19:28:38.869 WARN   [engine] - Unsupported link type '%!s(MISSING)', using default link
2018-03-05 19:28:38.869 DEBUG  [trigger-tibco-rest] - Registering handler [GET: /echo/:message]
2018-03-05 19:28:38.870 DEBUG  [trigger-tibco-rest] - Configured on port 8888
2018-03-05 19:28:38.870 DEBUG  [engine] - ActionRunner Service: Starting...
2018-03-05 19:28:38.870 DEBUG  [engine] - Starting worker with id '1'
2018-03-05 19:28:38.870 DEBUG  [engine] - Starting worker with id '2'
2018-03-05 19:28:38.870 DEBUG  [engine] - Starting worker with id '3'
2018-03-05 19:28:38.870 DEBUG  [engine] - Starting worker with id '4'
2018-03-05 19:28:38.870 DEBUG  [engine] - Starting worker with id '5'
2018-03-05 19:28:38.870 DEBUG  [engine] - ActionRunner Service: Started
2018-03-05 19:28:38.870 INFO   [engine] - Engine: Starting Services...
2018-03-05 19:28:38.870 INFO   [engine] - Engine: Started Services
2018-03-05 19:28:38.870 INFO   [engine] - Engine: Starting Triggers...
2018-03-05 19:28:38.870 DEBUG  [engine] - Trigger [ receive_http_message ]: Starting...
2018-03-05 19:28:38.870 DEBUG  [engine] - Trigger [ receive_http_message ]: Started
2018-03-05 19:28:38.870 INFO   [engine] - Trigger [ receive_http_message ]: Started
2018-03-05 19:28:38.870 INFO   [engine] - Engine: Triggers Started
2018-03-05 19:28:38.870 INFO   [engine] - Engine: Started
2018-03-05 19:28:48.098 INFO   [trigger-tibco-rest] - Received request for id 'receive_http_message'
2018-03-05 19:28:48.098 DEBUG  [engine] - iomd &data.IOMetadata{Input:map[string]*data.Attribute{"input":(*data.Attribute)(0xc42013aae0)}, Output:map[string]*data.Attribute{"output":(*data.Attribute)(0xc42013ab40)}}
2018-03-05 19:28:48.098 DEBUG  [basic-mapper] - Updated mapping def &{Type:1 Value:params.message MapTo:input}
2018-03-05 19:28:48.098 DEBUG  [engine] - Action 'github.com/TIBCOSoftware/flogo-contrib/action/flow' queued
2018-03-05 19:28:48.098 DEBUG  [engine] - Received work request
2018-03-05 19:28:48.098 DEBUG  [engine] - Dispatching work request
2018-03-05 19:28:48.098 DEBUG  [engine] - Action-Worker-1: Received Request
2018-03-05 19:28:48.098 INFO   [engine] - Running FlowAction for URI: 'res://flow:returnflow'
2018-03-05 19:28:48.098 DEBUG  [engine] - Creating Flow Instance: d101e23d07b2957abae201277f067881
2018-03-05 19:28:48.098 DEBUG  [engine] - Executing Flow Instance: d101e23d07b2957abae201277f067881
2018-03-05 19:28:48.098 DEBUG  [flowmodel-simple] - Enter Task 'log_2'
2018-03-05 19:28:48.098 DEBUG  [flowmodel-simple] - Task 'log_2' Ready
2018-03-05 19:28:48.098 DEBUG  [engine] - Scheduling task 'log_2'
2018-03-05 19:28:48.098 DEBUG  [engine] - Step: 1
2018-03-05 19:28:48.098 DEBUG  [engine] - Retrieved item from Flow Instance work queue
2018-03-05 19:28:48.099 DEBUG  [flowmodel-simple] - Eval Task 'log_2'
2018-03-05 19:28:48.099 INFO   [activity-flogo-log] - 'log ' - FlowInstanceID [d101e23d07b2957abae201277f067881], Flow [returnflow], Task []
2018-03-05 19:28:48.099 DEBUG  [engine] - SET OUTPUT: message = 'log ' - FlowInstanceID [d101e23d07b2957abae201277f067881], Flow [returnflow], Task []

2018-03-05 19:28:48.099 DEBUG  [engine] - SetAttr: message = 'log ' - FlowInstanceID [d101e23d07b2957abae201277f067881], Flow [returnflow], Task []
2018-03-05 19:28:48.099 DEBUG  [flowmodel-simple] - Task 'log_2' is done
2018-03-05 19:28:48.099 DEBUG  [flowmodel-simple] - Task 'log_2' has 1 outgoing links
2018-03-05 19:28:48.099 DEBUG  [flowmodel-simple] - Task 'log_2': Following Link  to task 'actreturn_3'
2018-03-05 19:28:48.099 DEBUG  [flowmodel-simple] - Enter Task 'actreturn_3'
2018-03-05 19:28:48.099 DEBUG  [flowmodel-simple] - Task 'actreturn_3' has 1 incoming Links
2018-03-05 19:28:48.099 DEBUG  [flowmodel-simple] - Task 'actreturn_3': Link from Task 'log_2' has status 'true'
2018-03-05 19:28:48.099 DEBUG  [flowmodel-simple] - Task 'actreturn_3' Ready
2018-03-05 19:28:48.099 DEBUG  [engine] - Scheduling task 'actreturn_3'
2018-03-05 19:28:48.099 DEBUG  [engine] - Step: 2
2018-03-05 19:28:48.099 DEBUG  [engine] - Retrieved item from Flow Instance work queue
2018-03-05 19:28:48.099 DEBUG  [flowmodel-simple] - Eval Task 'actreturn_3'
2018-03-05 19:28:48.099 DEBUG  [activity-flogo-return] - Mappings: [map[mapTo:output type:assign value:$flow.input]]
2018-03-05 19:28:48.099 WARN   [engine] - Unhandled Error executing activity ''[github.com/TIBCOSoftware/flogo-contrib/activity/actreturn] : interface conversion: interface {} is string, not float64

2018-03-05 19:28:48.099 DEBUG  [engine] - StackTrace: goroutine 51 [running]:
runtime/debug.Stack(0x1478326, 0x31, 0xc420188540)
	/usr/local/Cellar/go/1.10/libexec/src/runtime/debug/stack.go:24 +0xa7
return-6/vendor/github.com/TIBCOSoftware/flogo-contrib/action/flow/instance.(*TaskInst).EvalActivity.func1(0xc4201868c0, 0xc420209da0, 0xc420209d98)
	/Users/fcastill/flogo-engine/return-6/src/return-6/vendor/github.com/TIBCOSoftware/flogo-contrib/action/flow/instance/taskinst.go:303 +0x377
panic(0x13ebfa0, 0xc420184180)
	/usr/local/Cellar/go/1.10/libexec/src/runtime/panic.go:505 +0x229
return-6/vendor/github.com/TIBCOSoftware/flogo-lib/core/mapper.NewMapperDefFromAnyArray(0xc42001f110, 0x1, 0x1, 0xc42018ab70, 0x1, 0x1)
	/Users/fcastill/flogo-engine/return-6/src/return-6/vendor/github.com/TIBCOSoftware/flogo-lib/core/mapper/util.go:59 +0x36c
return-6/vendor/github.com/TIBCOSoftware/flogo-contrib/activity/actreturn.(*ReturnActivity).Eval(0xc42000e060, 0x14bc4a0, 0xc4201868c0, 0x39, 0xc420139058, 0xc4201863c0)
	/Users/fcastill/flogo-engine/return-6/src/return-6/vendor/github.com/TIBCOSoftware/flogo-contrib/activity/actreturn/activity.go:41 +0x175
return-6/vendor/github.com/TIBCOSoftware/flogo-contrib/action/flow/instance.(*TaskInst).EvalActivity(0xc4201868c0, 0x1468f00, 0x0, 0x0)
	/Users/fcastill/flogo-engine/return-6/src/return-6/vendor/github.com/TIBCOSoftware/flogo-contrib/action/flow/instance/taskinst.go:334 +0x33d
return-6/vendor/github.com/TIBCOSoftware/flogo-contrib/action/flow/model/simple.(*TaskBehavior).Eval(0x16f9438, 0x14bcc20, 0xc4201868c0, 0xc4201740c0, 0x144a000, 0xc4201884f0)
	/Users/fcastill/flogo-engine/return-6/src/return-6/vendor/github.com/TIBCOSoftware/flogo-contrib/action/flow/model/simple/taskbehavior.go:75 +0x14b
return-6/vendor/github.com/TIBCOSoftware/flogo-contrib/action/flow/instance.(*IndependentInstance).execTask(0xc4201740c0, 0x14bb7e0, 0x16f9438, 0xc4201868c0)
	/Users/fcastill/flogo-engine/return-6/src/return-6/vendor/github.com/TIBCOSoftware/flogo-contrib/action/flow/instance/instances.go:229 +0x222
return-6/vendor/github.com/TIBCOSoftware/flogo-contrib/action/flow/instance.(*IndependentInstance).DoStep(0xc4201740c0, 0x8)
	/Users/fcastill/flogo-engine/return-6/src/return-6/vendor/github.com/TIBCOSoftware/flogo-contrib/action/flow/instance/instances.go:175 +0x22e
return-6/vendor/github.com/TIBCOSoftware/flogo-contrib/action/flow.(*FlowAction).Run.func1(0x14b8360, 0xc4201fe000, 0xc4201740c0, 0xc420174000, 0xc4201f6010, 0xc4201f6008)
	/Users/fcastill/flogo-engine/return-6/src/return-6/vendor/github.com/TIBCOSoftware/flogo-contrib/action/flow/action.go:327 +0x27e
created by return-6/vendor/github.com/TIBCOSoftware/flogo-contrib/action/flow.(*FlowAction).Run
	/Users/fcastill/flogo-engine/return-6/src/return-6/vendor/github.com/TIBCOSoftware/flogo-contrib/action/flow/action.go:302 +0x47e

2018-03-05 19:28:48.099 ERROR  [engine] - Execution failed for Activity[] in Flow[returnflow] - interface conversion: interface {} is string, not float64
2018-03-05 19:28:48.099 ERROR  [flowmodel-simple] - Error evaluating activity 'actreturn_3'[github.com/TIBCOSoftware/flogo-contrib/activity/actreturn] - interface conversion: interface {} is string, not float64
2018-03-05 19:28:48.099 DEBUG  [engine] - AddAttr - name: {Error.activity}, type: string, value:
2018-03-05 19:28:48.099 DEBUG  [engine] - AddAttr - name: {Error.message}, type: string, value:interface conversion: interface {} is string, not float64
2018-03-05 19:28:48.099 DEBUG  [engine] - AddAttr - name: {Error.type}, type: string, value:unhandled
2018-03-05 19:28:48.099 DEBUG  [engine] - Done Executing flow instance [d101e23d07b2957abae201277f067881] - Status: 700
2018-03-05 19:28:48.099 INFO   [engine] - Flow instance [d101e23d07b2957abae201277f067881] Failed
2018-03-05 19:28:48.099 DEBUG  [engine] - Action-Worker-1: Completed Request
2018-03-05 19:28:48.099 DEBUG  [engine] - Action 'github.com/TIBCOSoftware/flogo-contrib/action/flow' returned
```

**Comment by mellistibco** [comment]
hey @fcastill is this still an issue?
