### ISSUE TITLE
Subflow error - runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by philippegabert** [TIBCOSoftware/flogo-contrib#260]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[] enhancement request
[] feature request
[] support request
[] general question
```

**Current behavior (how does the issue manifest):**
Application is not working and I have the current stack trace:
```
2018-06-26 13:41:01.174 DEBUG  [flowmodel-simple] - Eval Task 'subflow_3'
2018-06-26 13:41:01.176 DEBUG  [activity-flogo-subFlow] - Starting SubFlow: res://flow:subflow
2018-06-26 13:41:01.178 WARN   [engine] - Unhandled Error executing activity 'subflow'[github.com/TIBCOSoftware/flogo-contrib/activity/subflow] : runtime error: invalid memory address or nil pointer dereference

2018-06-26 13:41:01.184 DEBUG  [engine] - StackTrace: goroutine 20 [running]:
runtime/debug.Stack(0x39adf2, 0x31, 0x10ec7880)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
app-build/vendor/github.com/TIBCOSoftware/flogo-contrib/action/flow/instance.(*TaskInst).EvalActivity.func1(0x10f0c510, 0x10e37e3c, 0x10e37e38)
	/tmp/flogo-web/build/server/local/engines/app-build/src/app-build/vendor/github.com/TIBCOSoftware/flogo-contrib/action/flow/instance/taskinst.go:318 +0x2d4
panic(0x344a90, 0x5737a8)
	/usr/local/go/src/runtime/panic.go:491 +0x204
app-build/vendor/github.com/TIBCOSoftware/flogo-contrib/activity/subflow.(*SubFlowActivity).Eval(0x10e0c8c8, 0x545980, 0x10f0c510, 0x37, 0x10e61910, 0xe)
	/tmp/flogo-web/build/server/local/engines/app-build/src/app-build/vendor/github.com/TIBCOSoftware/flogo-contrib/activity/subflow/activity.go:70 +0x160
app-build/vendor/github.com/TIBCOSoftware/flogo-contrib/action/flow/instance.(*TaskInst).EvalActivity(0x10f0c510, 0x38c200, 0x0, 0x0)
	/tmp/flogo-web/build/server/local/engines/app-build/src/app-build/vendor/github.com/TIBCOSoftware/flogo-contrib/action/flow/instance/taskinst.go:349 +0x2ec
app-build/vendor/github.com/TIBCOSoftware/flogo-contrib/action/flow/model/simple.(*TaskBehavior).Eval(0x59d8a4, 0x545e58, 0x10f0c510, 0x10e57d40, 0xc, 0x0)
	/tmp/flogo-web/build/server/local/engines/app-build/src/app-build/vendor/github.com/TIBCOSoftware/flogo-contrib/action/flow/model/simple/taskbehavior.go:75 +0xf8
app-build/vendor/github.com/TIBCOSoftware/flogo-contrib/action/flow/instance.(*IndependentInstance).execTask(0x10e57d40, 0x545108, 0x59d8a4, 0x10f0c510)
	/tmp/flogo-web/build/server/local/engines/app-build/src/app-build/vendor/github.com/TIBCOSoftware/flogo-contrib/action/flow/instance/instances.go:229 +0xa74
app-build/vendor/github.com/TIBCOSoftware/flogo-contrib/action/flow/instance.(*IndependentInstance).DoStep(0x10e57d40, 0x8)
	/tmp/flogo-web/build/server/local/engines/app-build/src/app-build/vendor/github.com/TIBCOSoftware/flogo-contrib/action/flow/instance/instances.go:175 +0x220
app-build/vendor/github.com/TIBCOSoftware/flogo-contrib/action/flow.(*FlowAction).Run.func1(0x542e38, 0x10e0d218, 0x10e57d40, 0x10e57d00, 0x10e15214, 0x10e15210)
	/tmp/flogo-web/build/server/local/engines/app-build/src/app-build/vendor/github.com/TIBCOSoftware/flogo-contrib/action/flow/action.go:327 +0x224
created by app-build/vendor/github.com/TIBCOSoftware/flogo-contrib/action/flow.(*FlowAction).Run
	/tmp/flogo-web/build/server/local/engines/app-build/src/app-build/vendor/github.com/TIBCOSoftware/flogo-contrib/action/flow/action.go:302 +0x364

2018-06-26 13:41:01.193 ERROR  [engine] - Execution failed for Activity[subflow] in Flow[callsubflow] - runtime error: invalid memory address or nil pointer dereference
2018-06-26 13:41:01.195 ERROR  [flowmodel-simple] - Error evaluating activity 'subflow_3'[github.com/TIBCOSoftware/flogo-contrib/activity/subflow] - runtime error: invalid memory address or nil pointer dereference
2018-06-26 13:41:01.196 DEBUG  [engine] - AddAttr - name: _E.activity, type: string, value:subflow
2018-06-26 13:41:01.200 DEBUG  [engine] - AddAttr - name: _E.message, type: string, value:runtime error: invalid memory address or nil pointer dereference
2018-06-26 13:41:01.202 DEBUG  [engine] - AddAttr - name: _E.type, type: string, value:unhandled
2018-06-26 13:41:01.206 DEBUG  [engine] - AddAttr - name: _E.data, type: object, value:<nil>
2018-06-26 13:41:01.210 DEBUG  [engine] - AddAttr - name: _E.code, type: string, value:
2018-06-26 13:41:01.213 DEBUG  [engine] - Done Executing flow instance [c2ae2727ff325b70d33eef1f0c2d54a4] - Status: 700
2018-06-26 13:41:01.216 INFO   [engine] - Flow instance [c2ae2727ff325b70d33eef1f0c2d54a4] Failed
```
**Expected behavior:**
Subflow is called normally

**Minimal steps to reproduce the problem (not required if feature enhancement):**
See attached file (subflow.json)
[subflow.json.txt](https://github.com/TIBCOSoftware/flogo-contrib/files/2135499/subflow.json.txt)

**What is the motivation / use case for changing the behavior?**
N/A
**Please tell us about your environment (Operating system, docker version, browser & verison if webui, etc):**

**Flogo version (CLI & contrib/lib. If unknown, leave empty or state unknown):** 0.X.X
Latest version of Flogo 0.5.4
**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by fm-tibco** [comment]
Fixed in pull request #262
